<?php
/**
 * @file
 * advertisement.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function advertisement_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => '1',
  'title' => 'Advertisement ad example',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => 'd54efb65-7fc7-4337-a46a-9d7ae3bde8c4',
  'type' => 'advertisement_ad',
  'language' => 'en',
  'created' => '1377630165',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '21bec261-5d6e-4e13-a415-925fd8d39aaa',
  'revision_uid' => '1',
  'title_field' => array(
    'en' => array(
      0 => array(
        'value' => 'Advertisement ad example',
        'format' => NULL,
        'safe_value' => 'Advertisement ad example',
      ),
    ),
  ),
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Etiam semper porta orci; sed posuere nisi iaculis et. Mauris bibendum tincidunt lorem, dictum luctus sapien eleifend eget. Mauris sed scelerisque tortor, ut consequat sem. Donec auctor pellentesque massa eget viverra. Mauris eget justo venenatis dolor suscipit lacinia ut ut eros? Nulla a enim pellentesque, rutrum ligula eget, posuere augue. Fusce quam nulla, malesuada in nibh eu, euismod commodo nibh. Proin imperdiet laoreet laoreet. Etiam vel ullamcorper nisi? Proin dignissim risus in imperdiet convallis.

Pellentesque libero neque, lobortis eu sem a, dapibus lacinia dolor. Aenean enim metus, tempus vitae nibh ut, dignissim malesuada dui. Suspendisse nec dolor in purus consequat porttitor eu in est. Duis vitae dui magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempus pulvinar enim, sit amet sodales tellus faucibus eget. Nam sit amet neque at nibh luctus hendrerit et tincidunt neque. Aenean rhoncus lectus id facilisis viverra. Etiam purus tortor, fermentum gravida molestie nec, vestibulum a risus. Sed laoreet massa eu erat congue pellentesque. Nulla ullamcorper elit et odio scelerisque, quis posuere tellus fringilla. Suspendisse ut vehicula ligula. Nulla volutpat.
',
        'summary' => '',
        'format' => 'commerce_order_message',
        'safe_value' => 'Etiam semper porta orci; sed posuere nisi iaculis et. Mauris bibendum tincidunt lorem, dictum luctus sapien eleifend eget. Mauris sed scelerisque tortor, ut consequat sem. Donec auctor pellentesque massa eget viverra. Mauris eget justo venenatis dolor suscipit lacinia ut ut eros? Nulla a enim pellentesque, rutrum ligula eget, posuere augue. Fusce quam nulla, malesuada in nibh eu, euismod commodo nibh. Proin imperdiet laoreet laoreet. Etiam vel ullamcorper nisi? Proin dignissim risus in imperdiet convallis.

Pellentesque libero neque, lobortis eu sem a, dapibus lacinia dolor. Aenean enim metus, tempus vitae nibh ut, dignissim malesuada dui. Suspendisse nec dolor in purus consequat porttitor eu in est. Duis vitae dui magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempus pulvinar enim, sit amet sodales tellus faucibus eget. Nam sit amet neque at nibh luctus hendrerit et tincidunt neque. Aenean rhoncus lectus id facilisis viverra. Etiam purus tortor, fermentum gravida molestie nec, vestibulum a risus. Sed laoreet massa eu erat congue pellentesque. Nulla ullamcorper elit et odio scelerisque, quis posuere tellus fringilla. Suspendisse ut vehicula ligula. Nulla volutpat.',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_advertisement_ad_campaigns' => array(
    'und' => array(
      0 => array(
        'target_id' => '55',
      ),
    ),
  ),
  'cid' => '0',
  'last_comment_name' => NULL,
  'last_comment_uid' => '1',
  'comment_count' => '0',
  'name' => 'admin',
  'picture' => '0',
  'data' => 'a:2:{s:17:"mimemail_textonly";b:0;s:7:"overlay";i:1;}',
  'date' => '2013-08-27 21:02:45 +0200',
);
  $nodes[] = array(
  'uid' => '1',
  'title' => 'Advertisement ad campaign example',
  'log' => '',
  'status' => '1',
  'comment' => '1',
  'promote' => '0',
  'sticky' => '0',
  'vuuid' => '9cdb0bd3-bdea-4ee7-9347-cf6a83307df9',
  'type' => 'advertisement_ad_campaign',
  'language' => 'en',
  'created' => '1377630199',
  'tnid' => '0',
  'translate' => '0',
  'uuid' => '70bd5a55-bf80-429a-9553-e4822d6641e4',
  'revision_uid' => '1',
  'title_field' => array(
    'en' => array(
      0 => array(
        'value' => 'Advertisement ad campaign example',
        'format' => NULL,
        'safe_value' => 'Advertisement ad campaign example',
      ),
    ),
  ),
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Donec at nunc vitae massa lacinia imperdiet. Ut in leo elementum, volutpat neque a, tempus nisi. Maecenas pulvinar vulputate tellus; nec consequat elit vulputate sed. Sed in ornare eros. Donec interdum volutpat magna, in adipiscing justo convallis at? Maecenas ut lacinia nisi, non blandit turpis. Donec erat quam, suscipit quis nibh sit amet, commodo consequat odio. Etiam eleifend enim nec felis congue tristique. Donec ultrices nec turpis quis ultricies. Sed vitae mi mi. Etiam semper pellentesque malesuada. Pellentesque dignissim fringilla orci, vitae lacinia leo fermentum sit amet. Donec eu condimentum purus?

In hac habitasse platea dictumst. Integer facilisis nulla ut sagittis fermentum! Cras non semper eros. Suspendisse ultricies egestas tempus. Maecenas id justo a urna sodales pulvinar a sit amet magna! Duis orci mi, scelerisque a elit nec, volutpat tincidunt lectus! Quisque accumsan tincidunt sodales. Sed sem est, posuere in lobortis ac, gravida ac turpis. Duis gravida tincidunt nibh id rutrum. Aliquam erat volutpat. Maecenas eget tincidunt libero.

Nam ultricies sapien sit amet congue fringilla. Praesent tincidunt felis in libero convallis condimentum? Praesent venenatis posuere.
',
        'summary' => '',
        'format' => 'commerce_order_message',
        'safe_value' => 'Donec at nunc vitae massa lacinia imperdiet. Ut in leo elementum, volutpat neque a, tempus nisi. Maecenas pulvinar vulputate tellus; nec consequat elit vulputate sed. Sed in ornare eros. Donec interdum volutpat magna, in adipiscing justo convallis at? Maecenas ut lacinia nisi, non blandit turpis. Donec erat quam, suscipit quis nibh sit amet, commodo consequat odio. Etiam eleifend enim nec felis congue tristique. Donec ultrices nec turpis quis ultricies. Sed vitae mi mi. Etiam semper pellentesque malesuada. Pellentesque dignissim fringilla orci, vitae lacinia leo fermentum sit amet. Donec eu condimentum purus?

In hac habitasse platea dictumst. Integer facilisis nulla ut sagittis fermentum! Cras non semper eros. Suspendisse ultricies egestas tempus. Maecenas id justo a urna sodales pulvinar a sit amet magna! Duis orci mi, scelerisque a elit nec, volutpat tincidunt lectus! Quisque accumsan tincidunt sodales. Sed sem est, posuere in lobortis ac, gravida ac turpis. Duis gravida tincidunt nibh id rutrum. Aliquam erat volutpat. Maecenas eget tincidunt libero.

Nam ultricies sapien sit amet congue fringilla. Praesent tincidunt felis in libero convallis condimentum? Praesent venenatis posuere.',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_advertisement_ads' => array(
    'und' => array(
      0 => array(
        'target_id' => '54',
      ),
    ),
  ),
  'cid' => '0',
  'last_comment_name' => NULL,
  'last_comment_uid' => '1',
  'comment_count' => '0',
  'name' => 'admin',
  'picture' => '0',
  'data' => 'a:2:{s:17:"mimemail_textonly";b:0;s:7:"overlay";i:1;}',
  'date' => '2013-08-27 21:03:19 +0200',
);
  return $nodes;
}
